# Generated by Django 4.2.8 on 2024-04-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCashback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('main_category', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=100)),
                ('cashback', models.FloatField()),
                ('nfc', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('card', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('main_category', models.CharField(max_length=100)),
                ('cashback', models.FloatField()),
            ],
        ),
    ]
